shopstream:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'shopstream') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'shopstream123') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'shopstream') }}"
      schema: analytics
      threads: 4
